Update libraries version to support custom first question
Wootric/WootricSDK-flutter pull request #5
Opened 2023-02-07 18:25 UTC by diegoserranoa

Update SDK to versions that support custom first question

2023-02-10 05:32 UTC, vijayradke requested changes

2023-02-10 05:32 UTC, vijayradke commented on ios/wootricsdk_flutter.podspec
>    s.platform = :ios, '9.0'
Looks like we didn't release 0.25.0 for iOS

2023-02-10 05:34 UTC, vijayradke requested changes
Once iOS SDK version 0.25.0 released then we are good with this changes.

2023-03-06 23:12 UTC, diegoserranoa commented
@vijayradke updated both iOS and Android version to point to latest releases!

2023-03-07 19:02 UTC, mpeirick approved these changes

2023-03-14 22:22 UTC, merged